spring:
    application:
        name: mock-h2
    datasource:
     url: jdbc:h2:mem:testdb
     username: testdb
     password: psw1234
    jpa:
     hibernate:
        ddl-auto: create
    h2:
     console:
        enabled: true
