spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://127.0.0.1:3306/cars
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: create
---
environment: test
spring:

  datasource:
    driver-class-name: org.h2.Driver
    username: test
    password: test
    url: jdbc:h2:mem:testdb
  jpa:
    database : h2

