spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cruddb
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: create-drop
    jackson:
      serialization:
        fail-on-empty-beans: false


---
environment: test
spring:

  datasource:
    driver-class-name: org.h2.Driver
    username: test
    password: test
    url: jdbc:h2:mem:testdb;SET DB_CLOSE_DELAY -1[*]'
  jpa:
    database: h2