spring:

    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password:
      url: jdbc:mysql://127.0.0.1:3306/cars
    jpa:
      database: mysql
      show_sql: true
      hibernate:
        ddl-auto: update
    jackson:
      serialization:
        fail-on-empty-beans: false
